export  SpaceVehicle, 
        Payload, Rocket, Capsule, Sattelite

"""
Anything a stage pushes into the air/space with its booster. Could be e.g. a sattelite or another rocket stage
"""
abstract type Payload end

"""
A stage in a rocket. Is part of the static description of a rocket. Has no concepts of
where it is in space, velocity and acceleration. Rockets exist mainly to be able to keep track
of the force generated by the boosters in the rocket, as well as keeping track of mass of the
rocket as fuel is getting consumed.
"""
mutable struct Rocket <: Payload
    payload::Payload
    booster::Booster
end

"""
Heat shield below and typically no rocket engines or fuel tanks
"""
mutable struct Capsule <: Payload
	mass::Float64
end

mutable struct Sattelite <: Payload
	mass::Float64
end

####################### SpaceVehicle #####################################

"Represents a rocket in flight, with all its stages and payload."
mutable struct SpaceVehicle
	active_stage::Payload
    body::RigidBody
	gravity::Bool		# Is rocket affected by gravity
end

function SpaceVehicle(stage::Rocket, gravity::Bool = true)
	body = RigidBody(mass(stage), 0.0)
	SpaceVehicle(stage, body, gravity)
end